version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "henriquesebastiao"
    target-branch: "dev"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "henriquesebastiao"
    target-branch: "dev"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "henriquesebastiao"
    target-branch: "dev"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "henriquesebastiao"
    target-branch: "dev"
    exclude-paths:
       - "requirements.txt"